### ISSUE TITLE
help on flashing please

### ISSUE THREAD

**Issue by thematrixdev** [PricelessToolkit/ESPBell-MAX#6]
Hello there.
I have got ESPBell-Max from your online store.
I have just got every hardware needed and started flashing.

I have installed Arduino IDE, ESP8266 boards and PubSubClient.
My OS is Ubuntu 23.10. Added user to `dialout` group and rebooted.
Plugging in the USB FTDI-USB, Arduino could identify `/dev/ttyUSB0`.

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/a220bf70-48c5-4d80-b56a-dc37a5958df3)

```
$ sudo dmesg -c
[ 2080.065194] usb 1-1: new full-speed USB device number 17 using xhci_hcd
[ 2080.220624] usb 1-1: New USB device found, idVendor=0403, idProduct=6001, bcdDevice= 6.00
[ 2080.220639] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2080.220644] usb 1-1: Product: FT232R USB UART
[ 2080.220648] usb 1-1: Manufacturer: FTDI
[ 2080.220651] usb 1-1: SerialNumber: B001BPLG
[ 2080.224813] ftdi_sio 1-1:1.0: FTDI USB Serial Device converter detected
[ 2080.224840] usb 1-1: Detected FT232R
[ 2080.225207] usb 1-1: FTDI USB Serial Device converter now attached to ttyUSB0
```

Unplug FTDI-USB. Connect ESPBell-Max to FTDI-USB.
No matter with `flash` button pressed or not, plugging in FTDI-USB, `/dev/ttyUSB0` is not detected on Arduino IDE.

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/e2a974db-ff0e-4cde-b994-9eabb3e22023)

```
sudo dmesg -c
sudo dmesg -c
...
```

or 

```
sudo dmesg -c
[ 2810.650571] usb usb1-port7: connect-debounce failed
```

Tried:
```
sudo systemctl stop ModemManager
sudo systemctl disable ModemManager
sudo reboot
```

I am using `RXD`, `TXD`, `GND` and `VCC`.
`VCC` is set to `3V3`.
FTDI-USB `RXD` to ESPBell-MAX `TX`.
FTDI-USB `TXD` to ESPBell-MAX `RX`.
FTDI-USB `GND` to ESPBell-MAX `GND`.
FTDI-USB `VCC` to ESPBell-MAX `3V3`.

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/3f834ab1-964c-47c5-ac7e-babac02ce777)

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/b685685c-c871-4d99-a167-a5beefab5ba1)

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/c0bd0648-034e-4918-a49d-9802a976178d)

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/52a8504b-c047-4bad-8805-b981f1647cc2)

Thanks.

**Comment by PricelessToolkit** [comment]
Hi, I have never used Arduino IDE with Linux so I can't say anything, but If Arduino detects COM port only when USB-TTL is not connected to ESPBell, only one thing comes to mind USB-TTL adapter cannot provide enough power so voltage drops and adapter stop working, or connection is incorrect, can you check voltage when ESPBell is connected? And check the connection again, almost always these are simple errors that are difficult to notice.

**Comment by thematrixdev** [comment]
> Hi, I have never used Arduino IDE with Linux so I can't say anything, but If Arduino detects COM port only when USB-TTL is not connected to ESPBell, only one thing comes to mind USB-TTL adapter cannot provide enough power so voltage drops and adapter stop working, or connection is incorrect, can you check voltage when ESPBell is connected? And check the connection again, almost always these are simple errors that are difficult to notice.

It works after getting another USB-TTL adapter:

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/b292eaa5-cac7-402b-8f49-d605ccec1ad2)

I plan to use ESPBell-MAX with this doorbell:

![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/06f68d74-acd7-4602-81ba-a92ae961d16b)

Should I connect DB1 and DB2 on ESPBell-MAX to doorbell 1 and 3?
i.e.
DB1 -> 1 or DB1 -> 3
DB2 to the other

Thanks.

**Comment by thematrixdev** [comment]
I am trying to wake up the board to see if the WIFI and MQTT configuration is correct.
Watching your Youtube video, shorting B+ and ET should power on the board.
However, mine did not power on.
![image](https://github.com/PricelessToolkit/ESPBell-MAX/assets/19472561/5f496ebd-6fd2-44cf-bee1-7c6e17423eb9)

**Comment by PricelessToolkit** [comment]
It's strange, if you connect DB1 to battery + and DB2 to battery - like 0.5 seconds it wakes up?.

**Comment by PricelessToolkit** [comment]
1 and 3 are the outside doorbell button wires Yes?

**Comment by PricelessToolkit** [comment]
I think one DB to 3 and a second DB to upper contact from 3

**Comment by thematrixdev** [comment]
> It's strange, if you connect DB1 to battery + and DB2 to battery - like 0.5 seconds it wakes up?.

No. I think it is physical issue on the board. Should I ship it back to you for checking?

Thanks.

**Comment by PricelessToolkit** [comment]
Can you contact me from a shop so I can identify your order

thanks

**Comment by thematrixdev** [comment]
I have got the replacement. It works with my doorbell now. Thank you very much!
