### ISSUE TITLE
Arduino Verification step calls an error

### ISSUE THREAD

**Issue by s1ugh34d** [PricelessToolkit/ESPBell-MAX#8]
Arduino: 1.8.19 (Linux), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

~/ESPBell-MAX_MQTT_Auto_Discovery/ESPBell-MAX_MQTT_Auto_Discovery.ino: In function 'void reconnect()':
ESPBell-MAX_MQTT_Auto_Discovery:81:15: error: 'class PubSubClient' has no member named 'setBufferSize'
   81 |     if(client.setBufferSize(380)){
      |               ^~~~~~~~~~~~~
exit status 1
'class PubSubClient' has no member named 'setBufferSize'

Should I just ignore this?

**Comment by PricelessToolkit** [comment]
No, I am using Arduino IDE 2.3.2 on Windows, and it is compiling without errors. Please check if you have installed the libraries correctly.

ESP8266WiFi at version 1.0
PubSubClient at version 2.8

**Comment by s1ugh34d** [comment]
I updated to 2.3.2 arduino and 2.8 PubSubClient and it verified fine, flash
success. The snap image on Ubuntu store is old for Arduino IDE.

Not code related but can the device be powered by the 3.3v input?

**Comment by PricelessToolkit** [comment]
Back side 3.3V? Yes but only for programming
